---
- hosts: all
  become: true

  tasks:
  - name: stop current running container
    command: docker stop simple-devops-container
    ignore_errors: yes

  - name: removed stopped container
    command: docker rm simple-devops-container
    ignore_errors: yes

  - name: remove docker image
    command: docker rmi ashishdevops/simple-devops-image
    ignore_errors: yes

  - name: copy everything
    copy:
      src: /opt/docker/
      dest: /opt/docker/

  - name: build docker image using war
    command: docker build -t simple-devops-image .
    args:
      chdir: /opt/docker

  - name: tag image to image name 
    command: docker tag simple-devops-image ashishdevops/simple-devops-image

  - name: push image to docker hub 
    shell: "docker push ashishdevops/simple-devops-image"

  - name: remove image from local  
    command: docker rmi ashishdevops/simple-devops-image simple-devops-image

  - name: pull image from docker hub  
    shell: docker pull ashishdevops/simple-devops-image

  - name: create container using simple-devops-image
    command: docker run -d --name simple-devops-container -p 8181:8080 ashishdevops/simple-devops-image
